version: "3.8"

services:
  caddy:
    image: caddy:2-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - "../sites/:/var/www/html/:ro"
      - "./caddyfiles/dev/:/etc/caddy/"
      # - "./caddyfiles/prod/:/etc/caddy/"

      # Caddy needs to mount /data and /config for persisted data
      - "./caddy/data/:/data/"
      - "./caddy/config/:/config/"
    depends_on:
      - "php"
  
  php:
    build:
      dockerfile: "./dockerfiles/php.dockerfile"
    volumes:
      - "../sites/:/var/www/html/:ro"
    depends_on:
      - mariadb

  mariadb:
    image: mariadb
    env_file:
      - "db.env"
    volumes:
      - "./db/mariadb:/var/lib/mysql"
